// Generated by Wrangler on Sun Aug 11 2024 13:06:44 GMT+0700 (Indochina Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH0_ISSUER_BASE_URL: string;
	AUTH0_CLIENT_ID: string;
	AUTH0_SESSION_AUTO_SAVE: false;
	AUTH0_AUDIENCE: string;
	CONTENT_API: string;
	CONTENT: Fetcher;
}
